### PR TITLE
11ty

### PR DESCRIPTION
**Pull request by edthedev**
- Adds `11ty` configuration files.
- Adds a GitHub Action to publish converted HTML output to the `gh-pages` branch each the main branch changes.
- Converts main page and `github-actions` pages to Markdown.
- Adds an `eleventy` page that describes this setup.
- Moves `examples` to root so that `11ty` knows not to modify them.
- MISSING: Does not do breadcrumb navigation. This is doable, but deserves a separate pull request.
-

### CODE REVIEW

**Comment by edthedev** [comment]
Note that this requires GitHub to store a public and private key pair.


Public key is stored here to allow deployment to the gh-pages branch:
image

Private key is stored here to allow the GitHub action to do the deployment to the gh-pages branch:
image

Note pull requests that originate in forks outside this organization do not have access to the private key (GitHub enforces this), since that would allow a malicious user to fork and update without permission.

**Review by jtgorman — APPROVED** [review]
I think we should just go ahead and merge in this pull request. If something breaks, we can fix it. I think I get the basic idea. Seems like there's template files with the html, and somehow 11ty cuts parts out of the md file and puts them in the template. 

I'm not sure if I'm going to have time this week to test this as much as I'd like. I'm guessing it's just fork the repo, apply the pull request, set up the keys, trigger the action....but still making up for some lost time and I don't want this floating out there so long we all forget about it ;).


Jon G

**Comment by edthedev** [comment]
@jtgorman Sounds good. It works when testing locally. 
Unless anyone else has comments, I will plan to merge this early some morning this week, when I have some time after to either revert or correct any issues.

**Comment by edthedev** [comment]
The site is being served from the `gh-pages` branch now.
Updating any markdown files and either pushing to the `master` branch or merging a pull request into the `master` branch will kick off the GitHub action which will regenerate the HTML and push it to the `gh-pages` branch.

**Comment by edthedev** [comment]
Note that doing a quick live edit on the Mardown files via the GitHub web interface also works fine.

**Pull request merged**
